[package]
name = "rtc"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3  # Optional: maximize optimization level
codegen-units = 1  # Optional: for better optimization across units
lto = true  # Optional: link-time optimization

[dependencies]
minifb = "0.27.0"
wide = "0.7.28"
